image: openjdk:11-jdk

variables:
  ANDROID_COMPILE_SDK: "33"
  SDK_TOOLS: "9123335" #latest version from https://developer.android.com/studio/#command-tools
  EMULATOR_VERSION: "24"

stages:
  - build
  - test

before_script:
  - apt-get --quiet update --yes
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${SDK_TOOLS}_latest.zip
  - unzip -q android-sdk.zip -d android-sdk-linux
  - rm android-sdk.zip
  - export ANDROID_HOME=$PWD/android-sdk-linux

  # create a latest folder that will have the updated version of the dependencies
  - mkdir $ANDROID_HOME/cmdline-tools/tools

  # the current hierarchy is android-sdk-linux/cmdline-tools/tools (but the depenencies are not in the tools folder)
  # move the necessary dependencies into the tools folder
  - mv $ANDROID_HOME/cmdline-tools/{lib,bin,source.properties,NOTICE.txt} $ANDROID_HOME/cmdline-tools/tools

  # create a latest folder that will have the updated version of the dependencies
  - mkdir $ANDROID_HOME/cmdline-tools/latest

  # define PATH for all executable files we will run (skdmanger, avdmanager, abd, emulator)
  - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools

  # sdkmanager is located in the tools/bin folder which we have specified in our PATH $ANDROID_HOME/cmdline-tools/tools/bin
  - sdkmanager --sdk_root=${ANDROID_HOME} --update > update.log
  - echo y | sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-${ANDROID_COMPILE_SDK}" "extras;google;m2repository" "extras;android;m2repository" > installPlatform.log
  - chmod +x ./gradlew

lintDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

# Make Project
assembleDebug:
  interruptible: true
  stage: build
  script:
    - ./gradlew assembleDebug


unit-test-job: # This job runs in the test stage.
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: [
        ./**/build/test-results/testDebugUnitTest/TEST-*.xml,
      ]
